"""Module: __init__
Stage: Library
Author: KafuuChino
Date: 2026-09-28
Description: AGILAB MedicalAI Core Library for Hemodialysis Data Science and Prognosis.
"""

from agilab_lib.analysis import (
    calculate_hotelling_t2,
    calculate_spe,
    calculate_spe_limit,
    calculate_t2_limit,
    fit_pca,
    prune_multivariate_outliers,
    summarize_components,
)
from agilab_lib.modeling import (
    DEFAULT_DISCRETE_COLUMNS,
    calculate_metrics,
    create_smote_pipeline,
    evaluate_model_cv_and_test,
    find_optimal_threshold,
    get_model_zoo,
    identify_categorical_features,
    run_benchmark_suite,
)
from agilab_lib.preprocessing import (
    DEFAULT_CONTINUOUS_COLUMNS,
    DISCRETE_COUNT_COLUMNS,
    HIGH_MISSING_DROPS,
    IDENTIFIER_COLUMNS,
    LABEL_COLUMN,
    LABEL_COLUMN_3YR,
    TARGET_LEAKAGE_COLUMNS,
    LongitudinalPreprocessor,
    build_feature_matrices,
    clean_clinical_bounds,
    deterministic_pruning,
    encode_categorical_features,
    engineer_features,
    load_baseline_data,
    load_longitudinal_cohort,
    process_continuous_features,
    quarantine_target_leakage,
    split_patient_cohort,
)
from agilab_lib.visualization import (
    plot_benchmark_pr_curves,
    plot_benchmark_roc_curves,
    plot_pca_loadings_biplot,
    plot_pca_scatter,
    plot_scree,
    plot_t2_vs_spe,
    plot_top_feature_importance,
)

__all__ = [
    "load_baseline_data",
    "load_longitudinal_cohort",
    "split_patient_cohort",
    "deterministic_pruning",
    "quarantine_target_leakage",
    "clean_clinical_bounds",
    "engineer_features",
    "process_continuous_features",
    "encode_categorical_features",
    "build_feature_matrices",
    "LongitudinalPreprocessor",
    "fit_pca",
    "summarize_components",
    "calculate_hotelling_t2",
    "calculate_spe",
    "calculate_t2_limit",
    "calculate_spe_limit",
    "prune_multivariate_outliers",
    "plot_scree",
    "plot_pca_scatter",
    "plot_pca_loadings_biplot",
    "plot_t2_vs_spe",
    "plot_benchmark_roc_curves",
    "plot_benchmark_pr_curves",
    "plot_top_feature_importance",
    "get_model_zoo",
    "identify_categorical_features",
    "create_smote_pipeline",
    "find_optimal_threshold",
    "calculate_metrics",
    "evaluate_model_cv_and_test",
    "run_benchmark_suite",
    "TARGET_LEAKAGE_COLUMNS",
    "IDENTIFIER_COLUMNS",
    "LABEL_COLUMN",
    "LABEL_COLUMN_3YR",
    "HIGH_MISSING_DROPS",
    "DEFAULT_CONTINUOUS_COLUMNS",
    "DISCRETE_COUNT_COLUMNS",
    "DEFAULT_DISCRETE_COLUMNS",
]
